name: "Prebuild dev container image"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  deploy:
    if: "${{ github.ref == 'refs/heads/main' }}"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      packages: "write"
      pull-requests: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Login to GitHub container registry"
        uses: "docker/login-action@v3"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Install devpod"
        run: |
          curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64"
          install -c -m 0755 devpod /usr/local/bin
          rm -f devpod
          devpod provider add docker
          devpod provider use docker
      - name: "Prebuild dev container image"
        run: |
          echo "Prebuilding image for $dir..."
          devpod build . --repository "ghcr.io/${{ github.repository }}/devcontainer"
