name: "Release"
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  deploy:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Release"
        uses: "softprops/action-gh-release@v2"
